# Generated by Django 3.2.4 on 2021-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210614_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
