# Generated by Django 3.2.4 on 2021-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='information_uz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='information_ru',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
