# Generated by Django 3.2.4 on 2021-09-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='information_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='information_uz',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(default=1, verbose_name='Informatsiya (ru)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_uz',
            field=models.TextField(default=None, verbose_name='Informatsiya (uz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='subject_ru',
            field=models.CharField(default=None, max_length=100, verbose_name='Nomi(ru)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subject_uz',
            field=models.CharField(default=None, max_length=100, verbose_name='Nomi(uz)'),
            preserve_default=False,
        ),
    ]
